# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "imperator-ext"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kristian Mandrup"]
  s.date = "2012-08-05"
  s.description = "Factories, Macros, REST helpers and Mongoid integration"
  s.email = "kmandrup@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "docs/Design.md",
    "lib/imperator-ext.rb",
    "lib/imperator/command-ext.rb",
    "lib/imperator/command/class_factory.rb",
    "lib/imperator/command/macros.rb",
    "lib/imperator/command/method_factory.rb",
    "lib/imperator/command/rest.rb",
    "lib/imperator/command/rest_helper.rb",
    "lib/imperator/factory.rb",
    "lib/imperator/mongoid.rb",
    "lib/imperator/mongoid/attribute_helper.rb",
    "lib/imperator/mongoid/command.rb",
    "lib/imperator/mongoid/command/rest.rb",
    "spec/imperator-ext/command/class_factory_spec.rb",
    "spec/imperator-ext/command/macros_spec.rb",
    "spec/imperator-ext/command/method_factory_spec.rb",
    "spec/imperator-ext/command/rest_helper_spec.rb",
    "spec/imperator-ext/command/rest_spec.rb",
    "spec/imperator-ext/mongoid/command_spec.rb",
    "spec/imperator-ext/mongoid/rest_command_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/kristianmandrup/imperator-ext"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Various extensions for Imperator"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<virtus>, [">= 0"])
      s.add_runtime_dependency(%q<imperator>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 2.8.0"])
      s.add_development_dependency(%q<rdoc>, [">= 3.12"])
      s.add_development_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<simplecov>, [">= 0.5"])
    else
      s.add_dependency(%q<virtus>, [">= 0"])
      s.add_dependency(%q<imperator>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 2.8.0"])
      s.add_dependency(%q<rdoc>, [">= 3.12"])
      s.add_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<simplecov>, [">= 0.5"])
    end
  else
    s.add_dependency(%q<virtus>, [">= 0"])
    s.add_dependency(%q<imperator>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 2.8.0"])
    s.add_dependency(%q<rdoc>, [">= 3.12"])
    s.add_dependency(%q<bundler>, [">= 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<simplecov>, [">= 0.5"])
  end
end

